-- 0003 — source aggregate (SPEC-001 §3.2, SPEC-002 §2).

CREATE TABLE source (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             uuid NOT NULL REFERENCES tenant(id),
  name                  text NOT NULL,
  class                 text NOT NULL,
  jurisdiction          text,
  permission_class      permission_class NOT NULL DEFAULT 'WRITE_UNCLEAR',
  permission_checked_at timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);

-- LICENSE_POLICY: a catalogue entry without a recorded licence is incomplete.
CREATE TABLE source_catalog_entry (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id      uuid NOT NULL REFERENCES tenant(id),
  source_id      uuid NOT NULL REFERENCES source(id),
  category       text NOT NULL,
  coverage_notes text NOT NULL,
  provenance     text NOT NULL,
  license        text NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE removal_recipe (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenant(id),
  source_id           uuid NOT NULL REFERENCES source(id),
  version             integer NOT NULL CHECK (version >= 1),
  signature           bytea NOT NULL,
  channel             text NOT NULL,
  verification_method text NOT NULL,
  freshness_at        timestamptz NOT NULL,
  enabled             boolean NOT NULL DEFAULT false,
  created_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_id, version)
);

-- VG-SEC-001: remote content is untrusted until proven otherwise, so tainted defaults TRUE.
CREATE TABLE source_record (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenant(id),
  source_id    uuid NOT NULL REFERENCES source(id),
  raw_ref      text NOT NULL,
  observed_at  timestamptz NOT NULL,
  content_hash char(64) NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  tainted      boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- SPEC-002 §2 defines exposure without a case_id column: the linkage is navigable in the
-- other direction through request_case.exposure_id, so no duplicate column is added.
CREATE TABLE exposure (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        uuid NOT NULL REFERENCES tenant(id),
  subject_id       uuid NOT NULL REFERENCES protected_subject(id),
  source_record_id uuid NOT NULL REFERENCES source_record(id),
  confidence       numeric(3,2) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
  -- VG-IDENT-003 / VG-DATA-009: a score without basis is unrepresentable.
  confidence_basis jsonb NOT NULL CHECK (jsonb_array_length(confidence_basis) > 0),
  truth_state      truth_state NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: exposure
ALTER TABLE exposure ENABLE ROW LEVEL SECURITY;
ALTER TABLE exposure FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON exposure
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: removal_recipe
ALTER TABLE removal_recipe ENABLE ROW LEVEL SECURITY;
ALTER TABLE removal_recipe FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON removal_recipe
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: source
ALTER TABLE source ENABLE ROW LEVEL SECURITY;
ALTER TABLE source FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON source
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: source_catalog_entry
ALTER TABLE source_catalog_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_catalog_entry FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON source_catalog_entry
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: source_record
ALTER TABLE source_record ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_record FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON source_record
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END
