-- 0005 — evidence, audit and operations (SPEC-001 §3.5, SPEC-002 §2), and the four
-- cycle-closing deferrable foreign keys.

CREATE TABLE evidence_artifact (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenant(id),
  case_id         uuid REFERENCES request_case(id),
  kind            text NOT NULL,
  digest          char(64) NOT NULL CHECK (digest ~ '^[0-9a-f]{64}$'),
  storage_ref     text NOT NULL,
  egress_class    egress_class NOT NULL,
  redaction_state text NOT NULL CHECK (redaction_state IN ('NONE','SCRUBBED','DENIED')),
  captured_at     timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- tenant_id intentionally has no foreign key: an audit row must survive even if a tenant row
-- is closed, and an append-only log that cascades is not append-only.
CREATE TABLE audit_event (
  id             bigserial PRIMARY KEY,
  tenant_id      uuid NOT NULL,
  actor          text NOT NULL,
  action         text NOT NULL,
  target_kind    text NOT NULL,
  target_id      uuid,
  correlation_id uuid NOT NULL,
  payload        jsonb NOT NULL DEFAULT '{}'::jsonb,
  at             timestamptz NOT NULL DEFAULT now()
);

-- VG-EVIDENCE-003 / VG-DATA-004: append-only by construction.
CREATE RULE audit_no_update AS ON UPDATE TO audit_event DO INSTEAD NOTHING;
CREATE RULE audit_no_delete AS ON DELETE TO audit_event DO INSTEAD NOTHING;

-- SPEC-002 §2 covers UPDATE and DELETE with rules. TRUNCATE is not covered by a rule and
-- would still empty the table, so append-only is completed here with a statement trigger.
CREATE FUNCTION audit_no_truncate() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_event is append-only: TRUNCATE is refused (VG-EVIDENCE-003)';
END;
$$;

CREATE TRIGGER audit_no_truncate BEFORE TRUNCATE ON audit_event
  FOR EACH STATEMENT EXECUTE FUNCTION audit_no_truncate();

CREATE TABLE provider_transport_run (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id      uuid NOT NULL REFERENCES tenant(id),
  transport_name text NOT NULL,   -- SPEC-001 §3.5 `provider`; see the §4 deviation table
  auth_mode      text NOT NULL CHECK (auth_mode IN ('OFFICIAL_API','OFFICIAL_FORM','OFFICIAL_MAIL')),
  egress_class   egress_class NOT NULL,
  started_at     timestamptz NOT NULL,
  outcome        text NOT NULL,
  cost_minor_units bigint,
  cost_currency    char(3) CHECK (cost_currency IS NULL OR cost_currency ~ '^[A-Z]{3}$'),
  created_at     timestamptz NOT NULL DEFAULT now(),
  CHECK ((cost_minor_units IS NULL) = (cost_currency IS NULL))
);

-- VG-EGRESS-002: a repair capsule is DLP-scrubbed before it leaves the boundary. The schema
-- cannot prove scrubbing, so the domain factory refuses apparent PII at construction and this
-- table stores only the sanitized text.
CREATE TABLE repair_capsule (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid NOT NULL REFERENCES tenant(id),
  fingerprint        text NOT NULL,
  sanitized_evidence text NOT NULL,
  expected           text NOT NULL,
  actual             text NOT NULL,
  pr_ref             text,
  created_at         timestamptz NOT NULL DEFAULT now()
);

-- Cycle-closing foreign keys (SPEC-002 §2 declares all four; no creation order satisfies them).
ALTER TABLE authority_grant ADD CONSTRAINT authority_grant_evidence_id_fkey
  FOREIGN KEY (evidence_id) REFERENCES evidence_artifact(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE verification_observation ADD CONSTRAINT verification_observation_evidence_id_fkey
  FOREIGN KEY (evidence_id) REFERENCES evidence_artifact(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE reappearance ADD CONSTRAINT reappearance_evidence_id_fkey
  FOREIGN KEY (evidence_id) REFERENCES evidence_artifact(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE reappearance ADD CONSTRAINT reappearance_prior_removed_event_id_fkey
  FOREIGN KEY (prior_removed_event_id) REFERENCES audit_event(id) DEFERRABLE INITIALLY DEFERRED;

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: audit_event
ALTER TABLE audit_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_event FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON audit_event
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: evidence_artifact
ALTER TABLE evidence_artifact ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_artifact FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON evidence_artifact
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: provider_transport_run
ALTER TABLE provider_transport_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_transport_run FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON provider_transport_run
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: repair_capsule
ALTER TABLE repair_capsule ENABLE ROW LEVEL SECURITY;
ALTER TABLE repair_capsule FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON repair_capsule
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END
