-- 0011 — the HTTP idempotency store (SPEC-003 §4.2, VG-ACTION-001).
--
-- WHY A DEDICATED TABLE, when the domain already has `ExternalAction.idempotency_key`:
-- they answer different questions. The DOMAIN key makes the EFFECT at-most-once and outlives this
-- record (SPEC-001 §3.4); the HTTP record makes the RESPONSE replayable, so a caller that retries
-- receives the original status and body rather than a second 201. SPEC-003 §4.2 says exactly this:
-- a key whose stored record has expired "is a new request; for §5.8 that is safe only because the
-- domain IdempotencyKey on the ExternalAction is the durable one and outlives the HTTP record."
--
-- The uniqueness constraint is what makes `begin` atomic. Two simultaneous requests resolve on this
-- index: one inserts, the other's ON CONFLICT finds the row and sees IN_FLIGHT. No application-level
-- locking is involved, and none would be reliable.
--
-- TENANT-SCOPED, and therefore in db/tenant-scoped-tables.txt so scripts/generate-rls.ts emits the
-- policy. Without RLS one tenant's key space would be visible to another, and a deliberately-crafted
-- key could collide with a victim tenant's — a cross-tenant information leak through the conflict
-- body, which reports the original resource id.

CREATE TABLE http_idempotency (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenant(id),
  method          text NOT NULL CHECK (length(method) > 0),
  -- The route TEMPLATE, e.g. /v1/cases/{caseId}/external-actions, never the resolved path:
  -- scoping by resolved path would make every case a different key space and defeat the protection.
  route_template  text NOT NULL CHECK (length(route_template) > 0),
  idempotency_key text NOT NULL CHECK (length(idempotency_key) BETWEEN 16 AND 255),
  state           text NOT NULL DEFAULT 'IN_FLIGHT' CHECK (state IN ('IN_FLIGHT','COMPLETED')),
  -- SHA-256 of the canonicalised request body. A different fingerprint is a 409, not a replay.
  fingerprint     char(64) NOT NULL CHECK (fingerprint ~ '^[0-9a-f]{64}$'),
  response_status integer,
  -- Stored as TEXT, not jsonb: a reparse could reorder keys and change the bytes a client sees, and
  -- the replay contract is that the original body is returned verbatim.
  response_body   text,
  resource_id     uuid,
  traceparent     text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  completed_at    timestamptz,
  -- Retention is 24 hours by default (SPEC-003 §4.2). Recorded as a column rather than computed at
  -- read time so a future policy change can vary it per route without a migration.
  expires_at      timestamptz NOT NULL,

  -- THE atomicity guarantee. Named so ON CONFLICT can target it by name and a rename cannot silently
  -- change which constraint the store relies on.
  CONSTRAINT http_idempotency_scope_key
    UNIQUE (tenant_id, method, route_template, idempotency_key),

  -- A COMPLETED row must carry its response; an IN_FLIGHT row must not carry one yet. This is what
  -- stops a replay from returning a NULL status as though it were a real answer.
  CONSTRAINT http_idempotency_completion_shape CHECK (
    (state = 'IN_FLIGHT' AND response_status IS NULL AND completed_at IS NULL) OR
    (state = 'COMPLETED' AND response_status IS NOT NULL AND completed_at IS NOT NULL
      AND response_body IS NOT NULL)
  ),

  -- Only a real HTTP status may be stored, so a defect cannot replay a fabricated one.
  CONSTRAINT http_idempotency_status_range CHECK (
    response_status IS NULL OR (response_status BETWEEN 200 AND 599)
  )
);

-- The lookup path: one row per scope, read by the full predicate.
CREATE INDEX http_idempotency_expiry_idx ON http_idempotency (tenant_id, expires_at);

-- A partial index on the in-flight rows, so reclaiming abandoned work (a crash between effect and
-- completion) does not scan completed history.
CREATE INDEX http_idempotency_inflight_idx ON http_idempotency (tenant_id, created_at)
  WHERE state = 'IN_FLIGHT';

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: http_idempotency
ALTER TABLE http_idempotency ENABLE ROW LEVEL SECURITY;
ALTER TABLE http_idempotency FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON http_idempotency
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END
