-- 0022 — the case-aggregate fields SPEC-003 §5.7 requires that the delivered tables do not carry.
--
-- TWO THINGS, both materialising names the specifications already use.
--
-- 1. `request_case.recipe_id`. §5.7.1's request names a `recipeId` and its 201 response echoes it, and
--    SPEC-001:82's `RequestCase` row lists `recipeId` among the entity's fields — but SPEC-002 §2's
--    `request_case` DDL has no such column, which is why EP-003's plan could not create one. The column is
--    NULLABLE: cases created before this migration (the seed's, and every row written by §5.7.1 before today)
--    genuinely have no recipe recorded, and NULL states that rather than inventing a recipe the case never
--    used.
--
-- 2. `human_gate`. SPEC-001 names `HumanGate` as a canonical entity (its vocabulary list forbids synonyms for
--    it), §5.7.5 records one and returns its `gateId`, and §5.7.6's timeline carries `HUMAN_GATE` entries — but
--    no specification gives it a field list or a table, and no execplan defines one either (checked: the
--    mentions in EP-001/EP-002 are the vocabulary list and the `HumanGateRequired` domain error, not a schema).
--    The columns below are exactly what §5.7.5's request and response require, and nothing more; the two
--    routing fields have no specification source and are recorded as an implementation choice in
--    `ASSUMPTIONS.md` §3.29.
--
-- `human_gate.detected_at` is the caller's fact ("when the gate was detected"), while `created_at` is when the
-- row was written. They are different facts and both are kept: a gate reported an hour late must not look like
-- a gate that happened an hour later.

ALTER TABLE request_case
  ADD COLUMN recipe_id uuid REFERENCES removal_recipe(id);

CREATE TABLE human_gate (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenant(id),
  case_id             uuid NOT NULL REFERENCES request_case(id),
  gate_kind           text NOT NULL,
  detected_at         timestamptz NOT NULL,
  evidence_artifact_id uuid REFERENCES evidence_artifact(id),
  attempted_bypass    boolean NOT NULL DEFAULT false,
  -- Where a human must look, and by when. No specification enumerates queues or service levels, so these are
  -- written from the port's DECLARED routing table rather than derived at read time: a later change to that
  -- table must not rewrite what an earlier gate was told.
  human_queue         text NOT NULL,
  service_level_due_at timestamptz NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);

-- The timeline for a case reads its gates in time order, and §5.7.5 is a per-case route.
CREATE INDEX human_gate_case_detected_at_idx ON human_gate (tenant_id, case_id, detected_at);

-- §5.7.1 refuses `409 CASE_ALREADY_EXISTS` for "the same subject × source × exposure with a LIVE case". The
-- rule is stated in the database rather than only in the handler, so two concurrent creates cannot both
-- succeed — the duplicate the conflict code exists to refuse. TERMINAL states are excluded because a new case
-- for the same triple is legitimate once the old one is finished, which is exactly what VG-REAPPEAR-001
-- requires after a reappearance.
CREATE UNIQUE INDEX request_case_live_uniq
  ON request_case (tenant_id, subject_id, source_id, exposure_id)
  WHERE truth_state NOT IN ('VERIFIED_REMOVED', 'VERIFIED_NOT_PRESENT', 'NOT_REMOVABLE');

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: human_gate
ALTER TABLE human_gate ENABLE ROW LEVEL SECURITY;
ALTER TABLE human_gate FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON human_gate
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END
