-- 0029 — `coverage_report`: the table SPEC-003 §5.16.1 and §5.16.2 read.
--
-- WHY THIS TABLE IS CREATED HERE AND HAS NO PRODUCER YET. §5.16.2 requires a coverage report to name what was
-- NOT checked — `sourcesSkipped` with a reason per source, a required `uncheckedRemainder`, `checkedFraction`
-- beside `sourcesTotal`, and `complete` — because "a partial report cannot state or imply 'no exposure found'"
-- (VG-DISC-002, SPEC-000 §7.1). The rows are produced by a DISCOVERY RUN (§5.4), and §5.4's `DiscoveryRun`
-- aggregate, its lifecycle states and its record of per-source attempts are defined by NO specification in
-- `.agent/specs` (verified by search: the identifiers `DiscoveryRun` and `CoverageReport` appear in none of
-- them, recorded in ASSUMPTIONS §3.34). So this node creates the TABLE OF RECORD and the two READ routes over
-- it, and does not invent the producer: a fabricated lifecycle would be a model no specification authorises,
-- and the §5.4 node that owns discovery is where it belongs.
--
-- The consequence is stated rather than hidden: until §5.4 lands, `/v1/coverage-reports` returns rows only if
-- something outside this repository writes them, and the database test for these routes inserts its own rows to
-- prove the READ path. A reader must not mistake that for a working discovery pipeline.
--
-- WHY THE SHAPE IS COLUMNS AND NOT ONE JSONB BLOB. `sourcesTotal`, `sourcesAttempted` and `sourcesSucceeded` are
-- the denominator pair §5.16.1/§5.16.2 report and SPEC-000 §7.4 forbids returning a percentage without; making
-- them columns means a report cannot be written without them. `checkedFraction` is NOT stored: it is derived at
-- read time from `sourcesAttempted / sourcesTotal`, because a stored fraction can disagree with its own
-- numerator and denominator — and the one thing a ratio must never do is contradict the counts beside it.
--
-- `complete` is derived too, and deliberately NOT from the counts: a report over 12 sources that attempted 12
-- and succeeded 12 is not necessarily complete, because a source can succeed at returning nothing. The producer
-- states completeness; this table records the statement and the counts, and §5.16.2's `uncheckedRemainder` is
-- what makes the statement checkable.

CREATE TABLE coverage_report (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             uuid NOT NULL REFERENCES tenant(id),
  subject_id            uuid REFERENCES protected_subject(id),
  -- The run that produced this report. Nullable because a report can be regenerated over a stored run whose
  -- row was retained, and §5.16.1 filters by it rather than requiring it.
  discovery_run_id      uuid,
  catalogue_id          text,
  generated_at          timestamptz NOT NULL,
  sources_total         integer NOT NULL CHECK (sources_total >= 0),
  sources_attempted     integer NOT NULL CHECK (sources_attempted >= 0),
  sources_succeeded     integer NOT NULL CHECK (sources_succeeded >= 0),
  -- Per-source reasons, as §5.16.2 renders them: [{"sourceId":…,"sourceName":…,"reason":…}]. An ARRAY rather
  -- than a child table because the report is an immutable snapshot of what was observed at one instant; a child
  -- table invites later edits to a document that is evidence.
  sources_skipped       jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- The sources that were DECLARED and never attempted. §5.16.2 makes this "required, non-empty-when-partial",
  -- and that rule is enforced where it can be: the CHECK below refuses a report that is not complete and names
  -- no unchecked remainder, which is exactly the "absence not established" defect VG-DISC-002 forbids.
  unchecked_remainder   jsonb NOT NULL DEFAULT '[]'::jsonb,
  complete              boolean NOT NULL,
  caveats               text[] NOT NULL DEFAULT '{}',
  created_at            timestamptz NOT NULL DEFAULT now(),
  CHECK (sources_attempted <= sources_total),
  CHECK (sources_succeeded <= sources_attempted),
  CHECK (complete OR jsonb_array_length(unchecked_remainder) > 0)
);

-- §5.16.1 lists newest-first with optional subject and run filters; §5.16.2 reads one by id.
CREATE INDEX coverage_report_tenant_generated_idx
  ON coverage_report (tenant_id, generated_at DESC);
CREATE INDEX coverage_report_subject_idx
  ON coverage_report (tenant_id, subject_id, generated_at DESC);
CREATE INDEX coverage_report_run_idx
  ON coverage_report (tenant_id, discovery_run_id);

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: coverage_report
ALTER TABLE coverage_report ENABLE ROW LEVEL SECURITY;
ALTER TABLE coverage_report FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON coverage_report
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END
