-- 0032 — the webhook binding table §6.1/§6.2/§6.3 require and no specification defines.
--
-- WHY A NEW TABLE. §6.1's path token is "an opaque, single-purpose capability resolved to one `(tenantId, caseId,
-- controllerId)` binding, rotated and revocable per controller; it is not a bearer credential and confers no scope".
-- §6.2 and §6.3 resolve a `providerKeyId` / `mailProviderKeyId` the same way ("unknown or retired provider key
-- binding" is a 404). NO SPECIFICATION DEFINES THE STORE: `controller` carries id/tenant_id/name/kind/jurisdiction/
-- contact_refs and NO token column, and no other table holds a provider key.
--
-- So this migration creates the table the CONTRACT's behaviour requires. It invents no domain concept: every column
-- below is named by §6's own text — a token that resolves to a binding, a key id, a retired/revoked state, and a
-- rotation instant — and the alternative (holding bindings in configuration) would make revocation a deployment
-- rather than an operation, which is exactly what "rotated and revocable per controller" rules out.
--
-- THE TOKEN IS STORED AS A HASH, NEVER IN THE CLEAR. A capability token that appears in a request path is written to
-- access logs, proxy logs and browser history the moment it is used; storing only its SHA-256 means a database
-- disclosure does not hand an attacker working tokens. The hash is UNKEYED because the token is 256 bits of entropy
-- (`gen_random_uuid()`-grade material is too small; a caller generates it), so there is nothing to guess — and a
-- keyed hash here would imply the token is low-entropy, which it must not be.
--
-- A BINDING IS ONE OF THREE KINDS, and the CHECKs keep each kind's required columns honest: a controller callback
-- names a case and a controller; a provider or mail-provider binding names a key id and a secret name.

CREATE TABLE webhook_binding (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenant(id),
  kind              text NOT NULL CHECK (kind IN ('CONTROLLER_CALLBACK', 'PROVIDER_CALLBACK', 'MAIL_TRACKING')),
  -- The advertised key id from `X-VG-Key-Id` for the provider kinds; NULL for a controller callback, whose
  -- credential is the path token rather than a signed header.
  provider_key_id   text,
  -- SHA-256 of the capability token, hex. Unique across tenants: a token that resolved in two tenants would make
  -- the tenant a function of the token's OTHER columns rather than of the token itself.
  token_hash        text UNIQUE,
  -- Where the shared secret comes from. A NAME, never the secret: SPEC-002 §4 and VG-SEC-002 keep secret material
  -- out of the application database, so this column is resolved through the `SecretResolver` port at verification.
  secret_name       text,
  case_id           uuid REFERENCES request_case(id),
  controller_id     uuid REFERENCES controller(id),
  status            text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RETIRED', 'REVOKED')),
  rotated_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  -- Each kind carries what its route needs to resolve, and nothing else.
  CHECK (kind <> 'CONTROLLER_CALLBACK' OR (token_hash IS NOT NULL AND case_id IS NOT NULL AND controller_id IS NOT NULL)),
  CHECK (kind = 'CONTROLLER_CALLBACK' OR (provider_key_id IS NOT NULL AND secret_name IS NOT NULL)),
  -- A CONTROLLER CALLBACK CARRIES NO HEADER KEY: §6.1's headers include `X-VG-Key-Id`, and this route's binding
  -- supplies its own secret, so a token binding with a key id would be two credentials for one capability.
  CHECK (kind <> 'CONTROLLER_CALLBACK' OR secret_name IS NOT NULL)
);

CREATE INDEX webhook_binding_key_idx ON webhook_binding (tenant_id, provider_key_id);

-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)
-- table: webhook_binding
ALTER TABLE webhook_binding ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_binding FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON webhook_binding
  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
-- RLS-GENERATED-END
