#!/usr/bin/env sh
# Evidence index builder (EP-001 M8, corrected).
#
# Sentinel: `evidence index: ok`
#
# WHY THIS SCRIPT EXISTS RATHER THAN AN INLINE FIND LOOP.
#
# The first version of the M8 index hashed every file under the evidence directories
# indiscriminately. Three of the nine recorded digests were stale within minutes,
# because those files are RUN TRANSCRIPTS whose content legitimately differs on every
# run:
#
#   * `.agent/evidence/EP-001/verify-progression.txt` is rewritten by every
#     `gate-foundation.sh` run;
#   * `.agent/evidence/EP-001/M6-local-sequence.txt` embeds test `duration_ms` values;
#   * `.agent/evidence/dependency-audit/sbom.cdx.json` embeds a random CycloneDX
#     `serialNumber` UUID and a `metadata.timestamp`.
#
# Recording a hash for a file that changes every run produces an index that is
# *guaranteed* to be wrong, which is worse than no index: DOD-025 requires evidence to
# be reproducible and tied to an exact identity, and a stale hash cannot do that.
#
# This script therefore classifies each artifact explicitly:
#
#   STABLE   content is a pure function of the repository state, so its digest is a
#            durable identity. These are indexed and are what DOD-029 can bind to.
#   VOLATILE content contains time, a UUID, or a measurement. These are indexed by
#            path and description but with the digest marked `volatile`, so no claim
#            of identity is made from them.
set -eu
export CI=true GIT_TERMINAL_PROMPT=0 GIT_PAGER=cat PAGER=cat DEBIAN_FRONTEND=noninteractive
cd "$(dirname "$0")/.."

NODE="${1:-EP-001}"
OUT=".agent/evidence/${NODE}/INDEX.txt"
mkdir -p ".agent/evidence/${NODE}"

digest() {
  node -e 'const c=require("node:crypto"),fs=require("node:fs");process.stdout.write(c.createHash("sha256").update(fs.readFileSync(process.argv[1])).digest("hex"))' "$1"
}

# Paths whose content legitimately varies between runs. Extend this list only with a
# stated reason; an unexplained entry here silently weakens the evidence index.
is_volatile() {
  case "$1" in
    */verify-progression.txt) return 0 ;;      # rewritten by every gate run
    */M6-local-sequence.txt)  return 0 ;;      # embeds test duration_ms values
    */sbom.cdx.json)          return 0 ;;      # embeds a random UUID + timestamp
    */sbom.cdx.sha256)        return 0 ;;      # digest OF a volatile file
    */mutation/run.txt)       return 0 ;;      # embeds per-test timing from the runner
    *) return 1 ;;
  esac
}

{
  printf '# VanishGraph %s evidence index\n' "$NODE"
  printf '# Generated by scripts/evidence-index.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '#\n'
  printf '# STABLE   a pure function of repository state; its digest is a durable identity\n'
  printf '# VOLATILE content embeds time, a UUID or a measurement; no identity is claimed\n'
  printf '#\n'
  printf '# %-8s  %-64s  %s\n' 'CLASS' 'SHA256' 'PATH'
} > "$OUT"

stable=0
volatile=0

for dir in ".agent/evidence/${NODE}" .agent/evidence/build .agent/evidence/dependency-audit .agent/evidence/mutation; do
  [ -d "$dir" ] || continue
  for f in $(find "$dir" -type f ! -name INDEX.txt ! -name evidence-index.sh | sort); do
    if is_volatile "$f"; then
      printf '# %-8s  %-64s  %s\n' 'VOLATILE' '(not recorded)' "$f" >> "$OUT"
      volatile=$((volatile + 1))
    else
      d=$(digest "$f") || { echo "evidence index: FAIL - cannot hash $f" >&2; exit 1; }
      printf '# %-8s  %-64s  %s\n' 'STABLE' "$d" "$f" >> "$OUT"
      stable=$((stable + 1))
    fi
  done
done

[ $((stable + volatile)) -gt 0 ] || { echo "evidence index: FAIL - no evidence artifacts found" >&2; exit 1; }

printf '\n# %s stable artifact(s) with durable digests; %s volatile transcript(s) not identity-bound\n' \
  "$stable" "$volatile" >> "$OUT"

echo "evidence index: $NODE - $stable stable, $volatile volatile"
echo "evidence index: ok"
