/**
 * Generate the row-level-security block for every tenant-scoped table (SPEC-002 RLS-1, MIG-6).
 *
 * One central list (`db/tenant-scoped-tables.txt`) decides which tables are isolated. This
 * program finds the migration that creates each table and writes the ENABLE/FORCE/CREATE
 * POLICY block into that same migration, between generated markers, so RLS always ships with
 * the table.
 *
 * Modes:
 *   --write   rewrite the generated blocks
 *   --check   re-derive every block and fail on any drift (used by the gates and by lint)
 *
 * It also refuses two classes of silent omission:
 *   * a table in the list whose CREATE TABLE cannot be found in any migration;
 *   * a migration that creates a table with a tenant_id column that the list does not name.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const PROJECT_ROOT = resolve(import.meta.dirname, '..');
const MIGRATIONS_DIR = join(PROJECT_ROOT, 'db', 'migrations');
const LIST_FILE = join(PROJECT_ROOT, 'db', 'tenant-scoped-tables.txt');

const BEGIN =
  '-- RLS-GENERATED-BEGIN (generated by scripts/generate-rls.ts; do not edit by hand)';
const END = '-- RLS-GENERATED-END';

export function tenantScopedTables(): string[] {
  return readFileSync(LIST_FILE, 'utf8')
    .split('\n')
    .map((line) => line.split('#')[0]?.trim() ?? '')
    .filter((line) => line.length > 0);
}

export function migrationFiles(): string[] {
  return readdirSync(MIGRATIONS_DIR)
    .filter((name) => /^\d{4}_[a-z0-9_]+\.sql$/.test(name))
    .sort()
    .map((name) => join(MIGRATIONS_DIR, name));
}

function createdTables(sql: string): string[] {
  const names: string[] = [];
  for (const match of sql.matchAll(/CREATE TABLE\s+(?:IF NOT EXISTS\s+)?([a-z_][a-z0-9_]*)/gi)) {
    if (match[1] !== undefined) names.push(match[1]);
  }
  return names;
}

function tableHasTenantColumn(sql: string, table: string): boolean {
  const pattern = new RegExp(
    `CREATE TABLE\\s+(?:IF NOT EXISTS\\s+)?${table}\\s*\\(([\\s\\S]*?)\\n\\);`,
    'i',
  );
  const body = sql.match(pattern)?.[1];
  return body !== undefined && /(^|\n)\s*tenant_id\s+uuid/i.test(body);
}

function blockFor(table: string): string {
  return [
    `ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE ${table} FORCE  ROW LEVEL SECURITY;`,
    '',
    `CREATE POLICY tenant_isolation ON ${table}`,
    `  USING      (tenant_id = current_setting('app.tenant_id', true)::uuid)`,
    `  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);`,
  ].join('\n');
}

export function renderMigration(file: string, tables: readonly string[]): string {
  const original = readFileSync(file, 'utf8');
  const head = (original.split(BEGIN)[0] ?? '').trimEnd();
  const owned = tables.filter((table) => createdTables(original).includes(table));
  if (owned.length === 0) {
    // This migration creates no tenant-scoped table: leave it exactly as it is, so --check
    // never reports phantom drift from trailing-newline normalisation.
    return original;
  }
  const sections = owned.map(
    (table) => `${BEGIN}\n-- table: ${table}\n${blockFor(table)}\n${END}`,
  );
  return `${head}\n\n${sections.join('\n\n')}\n`;
}

export function main(argv: readonly string[]): number {
  const mode = argv.includes('--write') ? 'write' : argv.includes('--check') ? 'check' : '';
  if (mode === '') {
    console.error('usage: node scripts/generate-rls.ts --write|--check');
    return 2;
  }
  const tables = tenantScopedTables();
  if (tables.length === 0) {
    console.error('rls generation: FAIL - the tenant-scoped table list is empty (RLS-1)');
    return 1;
  }
  const files = migrationFiles();
  const allSql = files.map((file) => readFileSync(file, 'utf8')).join('\n');

  const missing = tables.filter((table) => !createdTables(allSql).includes(table));
  if (missing.length > 0) {
    console.error(
      `rls generation: FAIL - listed as tenant-scoped but never created in a migration: ${missing.join(', ')}`,
    );
    return 1;
  }
  const unlisted = files.flatMap((file) => {
    const sql = readFileSync(file, 'utf8');
    return createdTables(sql)
      .filter((table) => tableHasTenantColumn(sql, table) && !tables.includes(table))
      .map((table) => `${table} (${file.replace(`${PROJECT_ROOT}/`, '')})`);
  });
  if (unlisted.length > 0) {
    console.error(
      `rls generation: FAIL - table has a tenant_id column but is not in db/tenant-scoped-tables.txt: ${unlisted.join(', ')}`,
    );
    return 1;
  }

  let drift = 0;
  for (const file of files) {
    const rendered = renderMigration(file, tables);
    const current = readFileSync(file, 'utf8');
    if (mode === 'write') {
      if (rendered !== current) {
        writeFileSync(file, rendered);
        console.log(`rls generation: wrote ${file.replace(`${PROJECT_ROOT}/`, '')}`);
      }
    } else if (rendered !== current) {
      drift += 1;
      console.error(
        `rls generation: FAIL - generated block differs in ${file.replace(`${PROJECT_ROOT}/`, '')}; run node scripts/generate-rls.ts --write`,
      );
    }
  }
  if (mode === 'check' && drift > 0) return 1;
  console.log(
    `rls generation: ${tables.length} tenant-scoped tables, ${files.length} migrations, drift ${drift}`,
  );
  console.log('rls generation: ok');
  return 0;
}

if (process.argv[1]?.replace(/\\/g, '/').endsWith('scripts/generate-rls.ts')) {
  process.exit(main(process.argv.slice(2)));
}
