/**
 * The Fastify application (SPEC-003 §1, §2.4).
 *
 * Two properties of this file matter more than its contents:
 *
 *  1. **`buildServer` never touches the network.** It constructs the instance and registers
 *     plugins; `listen` lives in a separate entry point. That is what lets every contract test
 *     drive the real HTTP boundary through `app.inject` with no port, no race, and no cleanup.
 *  2. **Plugin order is fixed and load-bearing.** Correlation runs first so every later error and
 *     log line carries the same `correlationId`; the error handler runs before anything that can
 *     throw; identity runs before tenancy because a tenant is derived FROM the validated token;
 *     and routes run last so they can rely on all of it. Reordering these silently breaks
 *     correlation on 401 responses — the failures that most need correlating.
 *
 * The server does not decide truth states, does not import `src/domain`, and does not open a
 * connection. Handlers dispatch application commands; enforcement lives behind the ports.
 */

import Fastify, { type FastifyInstance } from 'fastify';
import type { JsonSchemaToTsProvider } from '@fastify/type-provider-json-schema-to-ts';

import { healthRoutes, type HealthDependencies } from './routes/health.ts';
import { installCorrelation } from './plugins/correlation.ts';
import { installErrorHandler } from './plugins/error-handler.ts';

/**
 * The concrete Fastify type every route in this service is registered against.
 *
 * The logger parameter uses `FastifyBaseLogger` rather than pino's `Logger`: Fastify narrows the
 * logger internally, and naming pino here produced a type that `buildServer` could not return
 * (`Property 'msgPrefix' is missing`). The alias must describe what Fastify actually constructs,
 * not what its default logger happens to be.
 */
export type VgFastify = FastifyInstance<
  import('node:http').Server,
  import('node:http').IncomingMessage,
  import('node:http').ServerResponse,
  import('fastify').FastifyBaseLogger,
  JsonSchemaToTsProvider
>;

export interface ServerDependencies {
  /** Readiness probes (SPEC-003 §5.17). Injected so readiness reflects real dependency state. */
  readonly health: HealthDependencies;
  /** Build identity reported by `/v1/health`. */
  readonly version: string;
  readonly commit: string;
  /**
   * Identity resolution (SPEC-003 §3, SPEC-005). Absent means the identity plugin is not
   * registered, and every route except §5.17 refuses with 401 — the fail-closed default. EP-004
   * M3 supplies the real implementation; until then a server built without it cannot serve data
   * routes, which is the honest state rather than a bypass.
   */
  readonly identity?: IdentityResolver;
  /**
   * Tenancy (SPEC-003 §2.4, VG-TENANT-001). Absent has the same fail-closed meaning as above.
   */
  readonly tenancy?: TenancyResolver;
  readonly logLevel?: string;
}

/**
 * Resolve a caller from a bearer token.
 *
 * Returns the tenant id and scopes. A resolver that cannot verify the token returns undefined
 * rather than a partial identity: a half-resolved caller is how a request reaches a handler it
 * should not.
 */
export interface IdentityResolver {
  resolve(input: {
    readonly authorization: string | undefined;
    readonly correlationId: string;
  }): Promise<
    | {
        readonly ok: true;
        readonly tenantId: string;
        readonly subject: string;
        readonly scopes: readonly string[];
        readonly roles: readonly string[];
      }
    | { readonly ok: false; readonly code: string }
  >;
}

/** Bind a resolved identity to a tenant-scoped session (SPEC-003 §2.4). */
export interface TenancyResolver {
  /** Run `fn` with `app.tenant_id` set for the tenant, inside one transaction. */
  withTenant<T>(tenantId: string, fn: () => Promise<T>): Promise<T>;
}

/**
 * Build the application.
 *
 * Deliberately synchronous and side-effect free: no `listen`, no DNS, no connection.
 */
export function buildServer(deps: ServerDependencies): VgFastify {
  const app = Fastify({
    // The correlation id is generated by our own plugin, so Fastify's is disabled: two id
    // generators would produce two ids and the log/response pair would not join.
    genReqId: () => '',
    logger: {
      level: deps.logLevel ?? 'info',
      // Redaction at the logger, as a second line of defence behind the error envelope: even if a
      // handler logged a header object wholesale, these paths never reach the sink (VG-SEC-002).
      redact: {
        paths: [
          'req.headers.authorization',
          'req.headers.cookie',
          'req.headers["idempotency-key"]',
          'req.headers["x-vg-signature"]',
          'res.headers["set-cookie"]',
        ],
        censor: '[REDACTED]',
      },
    },
    // A route not in the registry must not be reachable. Handlers register only from ROUTES.
    ajv: { customOptions: { removeAdditional: false, coerceTypes: false, allErrors: false } },
  }).withTypeProvider<JsonSchemaToTsProvider>();

  // ORDER IS LOAD-BEARING. See the file header.
  //
  // Installed directly rather than through `app.register`: register() runs a plugin in an
  // encapsulated child context, so its hooks apply only to routes registered INSIDE that child.
  // Measured: registering these as plugins left `request.correlationId` empty, set no
  // `x-correlation-id` header, and bypassed the error envelope entirely for sibling routes.
  installCorrelation(app);
  installErrorHandler(app);

  app.register(healthRoutes, {
    deps: deps.health,
    version: deps.version,
    commit: deps.commit,
  });

  return app;
}

/**
 * Start listening. Separate from `buildServer` so tests never bind a port.
 *
 * Returns the bound address so the caller can report the real port when 0 was requested.
 */
export async function listen(
  app: VgFastify,
  options: { readonly port: number; readonly host: string },
): Promise<{ readonly port: number; readonly host: string }> {
  await app.listen({ port: options.port, host: options.host });
  const address = app.server.address();
  if (address === null || typeof address === 'string') {
    return { port: options.port, host: options.host };
  }
  return { port: address.port, host: options.host };
}
