/**
 * The `/v1` route registry — the single source of truth for the route catalogue.
 *
 * SPEC-003 §5 is the contract; this file is its machine-readable form. Two properties make it
 * worth having rather than documenting routes in prose:
 *
 *  1. `src/http/routes/**` registers AGAINST this registry, and a contract test asserts the
 *     registered set equals this set exactly. A route implemented but unregistered is a
 *     defect, and so is an entry with no implementation — neither can hide.
 *  2. It is generated from SPEC-003 by extraction and then reviewed. Hand-transcribing 78
 *     routes is how a scope gets silently dropped from one of them.
 *
 * SCOPE VOCABULARY IS CLOSED (SPEC-003 §3.3). Every `scopes` entry below appears in that
 * table, and the contract test asserts closure, so a typo such as `vg.subject.read` fails
 * the build rather than silently denying every request that needs it.
 *
 * `truthState` appears nowhere in this file and in no request schema: SM-6 makes a truth
 * state the output of a guarded command, never an input.
 *
 * MEASURED: SPEC-003 §5 has 78 routes across 17 groups, not 79. See the EP-004 §12
 * Surprises entry for the three-way count and for the §5.9.1 source defect that makes that
 * route's Scope line unparseable by a line-anchored extractor.
 */

/** The closed scope vocabulary of SPEC-003 §3.3. */
export const SCOPES = [
  'vg.actions.execute',
  'vg.actions.read',
  'vg.appeal.write',
  'vg.audit.read',
  'vg.authority.read',
  'vg.authority.write',
  'vg.cases.read',
  'vg.cases.write',
  'vg.coverage.read',
  'vg.discovery.read',
  'vg.discovery.run',
  'vg.evidence.read',
  'vg.evidence.read_content',
  'vg.evidence.write',
  'vg.exposures.assess',
  'vg.exposures.read',
  'vg.observations.read',
  'vg.observations.write',
  'vg.pii.reveal',
  'vg.policy.read',
  'vg.policy.write',
  'vg.recipes.write',
  'vg.sources.read',
  'vg.sources.write',
  'vg.subjects.read',
  'vg.subjects.write',
] as const;

export type Scope = (typeof SCOPES)[number];

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

/** Whether a route requires an `Idempotency-Key` (SPEC-003 §4.1). */
export type IdempotencyRequirement = 'required' | 'optional' | 'none';

/**
 * Parameters that raise a route's requirements ABOVE its declared base.
 *
 * SPEC-003 §5.1.6 and §5.1.8 are the reason this exists. Their Scope line reads
 * "Scope `vg.subjects.read` (`vg.pii.reveal` + step-up for `includeValue=true`)" — the base read is
 * permitted with the read scope alone, and revealing a VALUE additionally needs `vg.pii.reveal` and a
 * fresh step-up.
 *
 * MEASURED DEFECT this corrects: the registry originally declared `vg.pii.reveal` and `stepUp: true`
 * UNCONDITIONALLY on both routes, so `beginHandler` demanded the reveal scope for a MASKED read and
 * answered `403 INSUFFICIENT_SCOPE` to a caller the contract permits. The masked read is the route's
 * documented default, so the mistake denied the common case.
 *
 * The requirement is expressed as data rather than as a conditional inside a handler, so the
 * route-catalogue test can assert it and a second route with the same shape does not have to
 * reinvent it.
 */
export interface ConditionalRequirement {
  /** The query parameter that triggers the extra requirement. */
  readonly parameter: string;
  /** The value that triggers it. Only `'true'` occurs today. */
  readonly when: string;
  /** Scopes required IN ADDITION to the route's declared scopes. */
  readonly scopes: readonly Scope[];
  /** Whether a fresh step-up is additionally required. */
  readonly stepUp: boolean;
}

export interface RouteDefinition {
  /** The SPEC-003 §5 catalogue number, so a failure names the row it violates. */
  readonly id: string;
  readonly method: HttpMethod;
  readonly path: string;
  /** The §5 group, for example `5.1`. */
  readonly group: string;
  /** Required scopes; all must be held (SPEC-003 §3.2). Empty means token-only. */
  readonly scopes: readonly Scope[];
  /** True when step-up authentication is required in addition to the scopes. */
  readonly stepUp: boolean;
  readonly idempotency: IdempotencyRequirement;
  readonly successStatus: number;
  /** `VG-API-*` and related requirements this route serves. */
  readonly serves: readonly string[];
  /**
   * Requirements that apply only when a specific query parameter is present.
   *
   * Absent on every route whose requirements are unconditional, which is all of them except §5.1.6
   * and §5.1.8. Their Scope line reads
   * "Scope `vg.subjects.read` (`vg.pii.reveal` + step-up for `includeValue=true`)" — the base read
   * needs only the read scope, and revealing a VALUE additionally needs `vg.pii.reveal` and a fresh
   * step-up. Expressing that as data lets the route-catalogue test assert it and keeps a handler from
   * having to reimplement the rule.
   */
  readonly conditional?: readonly ConditionalRequirement[];
}

/** Every `/v1` route in the SPEC-003 §5 catalogue. */
export const ROUTES: readonly RouteDefinition[] = [
  {
    id: '5.1.1',
    method: 'POST',
    path: '/v1/subjects',
    group: '5.1',
    scopes: ['vg.subjects.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-IDENT-001', 'VG-AUTHZ-001', 'VG-POLICY-004', 'VG-API-023', 'VG-AUTHZ-002', 'VG-API-017', 'SPEC-005 §4'],
  },
  {
    id: '5.1.2',
    method: 'GET',
    path: '/v1/subjects',
    group: '5.1',
    scopes: ['vg.subjects.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.1.3',
    method: 'GET',
    path: '/v1/subjects/{subjectId}',
    group: '5.1',
    scopes: ['vg.subjects.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.1.4',
    method: 'PATCH',
    path: '/v1/subjects/{subjectId}',
    group: '5.1',
    scopes: ['vg.subjects.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-POLICY-002', 'VG-POLICY-004'],
  },
  {
    id: '5.1.5',
    method: 'POST',
    path: '/v1/subjects/{subjectId}/aliases',
    group: '5.1',
    scopes: ['vg.subjects.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-IDENT-002'],
  },
  {
    id: '5.1.6',
    method: 'GET',
    path: '/v1/subjects/{subjectId}/aliases',
    group: '5.1',
    scopes: ['vg.subjects.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
    conditional: [
      { parameter: 'includeValue', when: 'true', scopes: ['vg.pii.reveal'], stepUp: true },
    ],
  },
  {
    id: '5.1.7',
    method: 'POST',
    path: '/v1/subjects/{subjectId}/identifiers',
    group: '5.1',
    scopes: ['vg.subjects.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-SEC-002', 'SPEC-001 §3'],
  },
  {
    id: '5.1.8',
    method: 'GET',
    path: '/v1/subjects/{subjectId}/identifiers',
    group: '5.1',
    scopes: ['vg.subjects.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
    conditional: [
      { parameter: 'includeValue', when: 'true', scopes: ['vg.pii.reveal'], stepUp: true },
    ],
  },
  {
    id: '5.1.9',
    method: 'GET',
    path: '/v1/subjects/{subjectId}/location-history',
    group: '5.1',
    scopes: ['vg.subjects.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.1.10',
    method: 'POST',
    path: '/v1/subjects/{subjectId}/location-history',
    group: '5.1',
    scopes: ['vg.subjects.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: ['SPEC-001 §2'],
  },
  {
    id: '5.2.1',
    method: 'POST',
    path: '/v1/subjects/{subjectId}/authority-grants',
    group: '5.2',
    scopes: ['vg.authority.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-AUTHZ-001', 'VG-AUTHZ-002', 'VG-IDENT-001', 'VG-AUTHZ-014', 'VG-AUTH-032', 'VG-AUTHZ-016', 'VG-POLICY-001', 'SPEC-005 §3', 'SPEC-005 §4', 'SPEC-000 §8', 'SPEC-005 §11'],
  },
  {
    id: '5.2.2',
    method: 'GET',
    path: '/v1/subjects/{subjectId}/authority-grants',
    group: '5.2',
    scopes: ['vg.authority.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.2.3',
    method: 'POST',
    path: '/v1/authority-grants/{authorityGrantId}/revocations',
    group: '5.2',
    scopes: ['vg.authority.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-AUTHZ-001', 'VG-REAPPEAR-002', 'SPEC-001 §4.2'],
  },
  {
    id: '5.3.1',
    method: 'GET',
    path: '/v1/sources',
    group: '5.3',
    scopes: ['vg.sources.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-CHANNEL-002', 'VG-CHANNEL-003'],
  },
  {
    id: '5.3.2',
    method: 'POST',
    path: '/v1/sources',
    group: '5.3',
    scopes: ['vg.sources.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: [],
  },
  {
    id: '5.3.3',
    method: 'GET',
    path: '/v1/sources/{sourceId}',
    group: '5.3',
    scopes: ['vg.sources.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.3.4',
    method: 'PATCH',
    path: '/v1/sources/{sourceId}/permission-class',
    group: '5.3',
    scopes: ['vg.sources.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-CHANNEL-002'],
  },
  {
    id: '5.3.5',
    method: 'GET',
    path: '/v1/sources/{sourceId}/catalog-entries',
    group: '5.3',
    scopes: ['vg.sources.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-DISC-002'],
  },
  {
    id: '5.3.6',
    method: 'POST',
    path: '/v1/sources/{sourceId}/catalog-entries',
    group: '5.3',
    scopes: ['vg.sources.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: [],
  },
  {
    id: '5.3.7',
    method: 'POST',
    path: '/v1/sources/{sourceId}/recipes',
    group: '5.3',
    scopes: ['vg.recipes.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-CHANNEL-003'],
  },
  {
    id: '5.3.8',
    method: 'GET',
    path: '/v1/sources/{sourceId}/recipes',
    group: '5.3',
    scopes: ['vg.sources.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-REAPPEAR-002'],
  },
  {
    id: '5.3.9',
    method: 'GET',
    path: '/v1/recipes/{recipeId}',
    group: '5.3',
    scopes: ['vg.sources.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.3.10',
    method: 'POST',
    path: '/v1/recipes/{recipeId}/enablement',
    group: '5.3',
    scopes: ['vg.recipes.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-CHANNEL-002', 'VG-CHANNEL-003'],
  },
  {
    id: '5.4.1',
    method: 'POST',
    path: '/v1/discovery-runs',
    group: '5.4',
    scopes: ['vg.discovery.run'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 202,
    serves: ['VG-DISC-001'],
  },
  {
    id: '5.4.2',
    method: 'GET',
    path: '/v1/discovery-runs',
    group: '5.4',
    scopes: ['vg.discovery.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.4.3',
    method: 'GET',
    path: '/v1/discovery-runs/{discoveryRunId}',
    group: '5.4',
    scopes: ['vg.discovery.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.4.4',
    method: 'GET',
    path: '/v1/subjects/{subjectId}/candidate-records',
    group: '5.4',
    scopes: ['vg.exposures.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-IDENT-004', 'VG-DISC-002', 'SPEC-000 §7.1'],
  },
  {
    id: '5.4.5',
    method: 'GET',
    path: '/v1/source-records/{sourceRecordId}',
    group: '5.4',
    scopes: ['vg.discovery.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-SEC-001'],
  },
  {
    id: '5.5.1',
    method: 'GET',
    path: '/v1/exposures',
    group: '5.5',
    scopes: ['vg.exposures.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-IDENT-003', 'SPEC-001 §2', 'SPEC-000 §5'],
  },
  {
    id: '5.5.2',
    method: 'GET',
    path: '/v1/exposures/{exposureId}',
    group: '5.5',
    scopes: ['vg.exposures.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['SPEC-000 §5'],
  },
  {
    id: '5.5.3',
    method: 'POST',
    path: '/v1/exposures/{exposureId}/match-assessments',
    group: '5.5',
    scopes: ['vg.exposures.assess'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-IDENT-003', 'VG-IDENT-004'],
  },
  {
    id: '5.5.4',
    method: 'POST',
    path: '/v1/exposures/{exposureId}/disproofs',
    group: '5.5',
    scopes: ['vg.exposures.assess'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-DISC-002', 'SPEC-000 §5.1', 'SPEC-001 §4.2'],
  },
  {
    id: '5.5.5',
    method: 'GET',
    path: '/v1/exposures/{exposureId}/transitions',
    group: '5.5',
    scopes: ['vg.exposures.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['SPEC-001 §4.1'],
  },
  {
    id: '5.6.1',
    method: 'POST',
    path: '/v1/cases/{caseId}/policy-decisions',
    group: '5.6',
    scopes: ['vg.policy.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-POLICY-002', 'VG-POLICY-001', 'VG-CHANNEL-001', 'VG-POLICY-004'],
  },
  {
    id: '5.6.2',
    method: 'GET',
    path: '/v1/cases/{caseId}/policy-decisions',
    group: '5.6',
    scopes: ['vg.policy.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.6.3',
    method: 'GET',
    path: '/v1/policy-decisions/{policyDecisionId}',
    group: '5.6',
    scopes: ['vg.policy.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.6.4',
    method: 'GET',
    path: '/v1/jurisdiction-policies',
    group: '5.6',
    scopes: ['vg.policy.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-POLICY-001'],
  },
  {
    id: '5.7.1',
    method: 'POST',
    path: '/v1/cases',
    group: '5.7',
    scopes: ['vg.cases.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-POLICY-002'],
  },
  {
    id: '5.7.2',
    method: 'GET',
    path: '/v1/cases',
    group: '5.7',
    scopes: ['vg.cases.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.7.3',
    method: 'GET',
    path: '/v1/cases/{caseId}',
    group: '5.7',
    scopes: ['vg.cases.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.7.4',
    method: 'PATCH',
    path: '/v1/cases/{caseId}',
    group: '5.7',
    scopes: ['vg.cases.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['SPEC-001 §4.1'],
  },
  {
    id: '5.7.5',
    method: 'POST',
    path: '/v1/cases/{caseId}/human-gates',
    group: '5.7',
    scopes: ['vg.cases.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-OBS-002', 'VG-DISC-004', 'SPEC-001 §4.3'],
  },
  {
    id: '5.7.6',
    method: 'GET',
    path: '/v1/cases/{caseId}/timeline',
    group: '5.7',
    scopes: ['vg.cases.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-EVIDENCE-003'],
  },
  {
    id: '5.8.1',
    method: 'GET',
    path: '/v1/cases/{caseId}/external-actions',
    group: '5.8',
    scopes: ['vg.actions.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.8.2',
    method: 'POST',
    path: '/v1/cases/{caseId}/external-actions',
    group: '5.8',
    scopes: ['vg.actions.execute'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-ACTION-001', 'VG-EGRESS-001', 'VG-AUTHZ-001', 'VG-CHANNEL-003', 'VG-CHANNEL-002', 'VG-CHANNEL-001', 'VG-ACTION-005', 'VG-POLICY-004', 'VG-ACTION-004', 'SPEC-001 §4.2'],
  },
  {
    id: '5.8.3',
    method: 'POST',
    path: '/v1/external-actions/{externalActionId}/reconciliations',
    group: '5.8',
    scopes: ['vg.actions.execute'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-ACTION-002', 'SPEC-001 §4.1', 'SPEC-001 §4.2'],
  },
  {
    id: '5.8.4',
    method: 'POST',
    path: '/v1/external-actions/{externalActionId}/readback',
    group: '5.8',
    scopes: ['vg.actions.execute'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 202,
    serves: ['VG-ACTION-003', 'VG-VERIFY-001'],
  },
  {
    id: '5.8.5',
    method: 'GET',
    path: '/v1/external-actions/{externalActionId}',
    group: '5.8',
    scopes: ['vg.actions.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.8.6',
    method: 'GET',
    path: '/v1/cases/{caseId}/mail-pieces',
    group: '5.8',
    scopes: ['vg.actions.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-ACTION-004'],
  },
  {
    id: '5.9.1',
    method: 'POST',
    path: '/v1/cases/{caseId}/controller-responses',
    group: '5.9',
    scopes: ['vg.cases.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-VERIFY-004', 'SPEC-001 §3.4', 'SPEC-000 §5.1', 'SPEC-000 §7.6'],
  },
  {
    id: '5.9.2',
    method: 'GET',
    path: '/v1/cases/{caseId}/controller-responses',
    group: '5.9',
    scopes: ['vg.cases.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.9.3',
    method: 'POST',
    path: '/v1/cases/{caseId}/email-threads',
    group: '5.9',
    scopes: ['vg.cases.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: ['SPEC-001 §3.4'],
  },
  {
    id: '5.10.1',
    method: 'POST',
    path: '/v1/cases/{caseId}/verification-observations',
    group: '5.10',
    scopes: ['vg.observations.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-VERIFY-004', 'VG-VERIFY-001', 'VG-VERIFY-002', 'VG-VERIFY-003', 'SPEC-001 §4.2', 'SPEC-000 §5.1'],
  },
  {
    id: '5.10.2',
    method: 'GET',
    path: '/v1/cases/{caseId}/verification-observations',
    group: '5.10',
    scopes: ['vg.observations.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.10.3',
    method: 'GET',
    path: '/v1/verification-observations/{verificationObservationId}',
    group: '5.10',
    scopes: ['vg.observations.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.11.1',
    method: 'POST',
    path: '/v1/exposures/{exposureId}/reappearances',
    group: '5.11',
    scopes: ['vg.observations.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-REAPPEAR-001', 'VG-REAPPEAR-002', 'SPEC-001 §4.1'],
  },
  {
    id: '5.11.2',
    method: 'GET',
    path: '/v1/reappearances',
    group: '5.11',
    scopes: ['vg.observations.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.11.3',
    method: 'GET',
    path: '/v1/exposures/{exposureId}/reappearances',
    group: '5.11',
    scopes: ['vg.observations.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.12.1',
    method: 'POST',
    path: '/v1/evidence-artifacts',
    group: '5.12',
    scopes: ['vg.evidence.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-EVIDENCE-001'],
  },
  {
    id: '5.12.2',
    method: 'GET',
    path: '/v1/evidence-artifacts/{evidenceArtifactId}',
    group: '5.12',
    scopes: ['vg.evidence.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-EVIDENCE-002'],
  },
  {
    id: '5.12.3',
    method: 'GET',
    path: '/v1/evidence-artifacts/{evidenceArtifactId}/content',
    group: '5.12',
    scopes: ['vg.evidence.read_content'],
    stepUp: true,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-EVIDENCE-001'],
  },
  {
    id: '5.12.4',
    method: 'POST',
    path: '/v1/evidence-artifacts/{evidenceArtifactId}/integrity-checks',
    group: '5.12',
    scopes: ['vg.evidence.read'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: ['VG-EVIDENCE-001'],
  },
  {
    id: '5.12.5',
    method: 'GET',
    path: '/v1/cases/{caseId}/evidence-artifacts',
    group: '5.12',
    scopes: ['vg.evidence.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.13.1',
    method: 'GET',
    path: '/v1/cases/{caseId}/deadlines',
    group: '5.13',
    scopes: ['vg.cases.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-POLICY-001', 'SPEC-001 §3.4'],
  },
  {
    id: '5.13.2',
    method: 'POST',
    path: '/v1/cases/{caseId}/deadlines',
    group: '5.13',
    scopes: ['vg.cases.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 201,
    serves: [],
  },
  {
    id: '5.13.3',
    method: 'POST',
    path: '/v1/deadlines/{deadlineId}/satisfaction',
    group: '5.13',
    scopes: ['vg.cases.write'],
    stepUp: false,
    idempotency: 'required',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.14.1',
    method: 'POST',
    path: '/v1/cases/{caseId}/appeal-escalations',
    group: '5.14',
    scopes: ['vg.appeal.write'],
    stepUp: true,
    idempotency: 'required',
    successStatus: 201,
    serves: ['VG-CHANNEL-001', 'VG-SCOPE-005', 'SPEC-000 §8'],
  },
  {
    id: '5.14.2',
    method: 'GET',
    path: '/v1/cases/{caseId}/appeal-escalations',
    group: '5.14',
    scopes: ['vg.cases.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.14.3',
    method: 'GET',
    path: '/v1/appeal-escalations/{appealEscalationId}',
    group: '5.14',
    scopes: ['vg.cases.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.15.1',
    method: 'GET',
    path: '/v1/audit-events',
    group: '5.15',
    scopes: ['vg.audit.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-SEC-002', 'VG-EVIDENCE-003'],
  },
  {
    id: '5.15.2',
    method: 'GET',
    path: '/v1/audit-events/{auditEventId}',
    group: '5.15',
    scopes: ['vg.audit.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.16.1',
    method: 'GET',
    path: '/v1/coverage-reports',
    group: '5.16',
    scopes: ['vg.coverage.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.16.2',
    method: 'GET',
    path: '/v1/coverage-reports/{coverageReportId}',
    group: '5.16',
    scopes: ['vg.coverage.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-DISC-002', 'SPEC-000 §7.1', 'SPEC-000 §7.4'],
  },
  {
    id: '5.16.3',
    method: 'GET',
    path: '/v1/metrics/removal-effectiveness',
    group: '5.16',
    scopes: ['vg.coverage.read'],
    stepUp: false,
    idempotency: 'optional',
    successStatus: 200,
    serves: ['VG-OBS-002', 'SPEC-000 §5.1', 'SPEC-000 §7.6'],
  },
  {
    id: '5.17.1',
    method: 'GET',
    path: '/v1/health',
    group: '5.17',
    scopes: [],
    stepUp: false,
    idempotency: 'none',
    successStatus: 200,
    serves: [],
  },
  {
    id: '5.17.2',
    method: 'GET',
    path: '/v1/ready',
    group: '5.17',
    scopes: [],
    stepUp: false,
    idempotency: 'none',
    successStatus: 200,
    serves: ['VG-OPS-001', 'VG-OBS-025', 'SPEC-007 §7', 'SPEC-007 §7.2'],
  },
  {
    id: '5.17.3',
    method: 'GET',
    path: '/v1/live',
    group: '5.17',
    scopes: [],
    stepUp: false,
    idempotency: 'none',
    successStatus: 200,
    serves: ['VG-OBS-023'],
  },
  {
    id: '5.17.4',
    method: 'GET',
    path: '/v1/startup',
    group: '5.17',
    scopes: [],
    stepUp: false,
    idempotency: 'none',
    successStatus: 200,
    serves: ['SPEC-007 §7.1'],
  },
];

/**
 * Webhook ingress routes (SPEC-003 §6).
 *
 * Kept OUT of ROUTES on purpose: these are authenticated by signature and a capability
 * token, not by a bearer scope. SPEC-003 §3.3 states `vg.webhooks.ingest` is deliberately
 * absent from the scope vocabulary so no token can carry a scope that would let a caller
 * forge ingress. A contract test asserts no scope in ROUTES is a webhook scope.
 */
export const WEBHOOK_ROUTES = [
  { id: '6.1', method: 'POST', path: '/v1/webhooks/controller-callbacks/{controllerCallbackToken}' },
  { id: '6.2', method: 'POST', path: '/v1/webhooks/provider-callbacks/{providerKeyId}' },
  { id: '6.3', method: 'POST', path: '/v1/webhooks/mail-tracking/{mailProviderKeyId}' },
] as const;

/** Look up a route by method and path template. */
export function findRoute(method: string, path: string): RouteDefinition | undefined {
  return ROUTES.find((route) => route.method === method && route.path === path);
}

/** The routes that must carry an `Idempotency-Key` (SPEC-003 §4.1). */
export const EFFECT_BEARING_ROUTES: readonly RouteDefinition[] = ROUTES.filter(
  (route) => route.idempotency === 'required',
);
